# This is a basic workflow to help you get started with Actions

name: Deploy to Prod

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy to portal.ppiuk.org
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: portal.ppiuk.org
          key: ${{ secrets.DEPLOY_KEY }}
          username: ubuntu
          script: cd ~/repos/ppi-portal-frontend;git fetch --all; git reset --hard origin/main; npm ci; npm run build; sudo rm -rf /var/www/ppi-portal-frontend; sudo mv build/ /var/www/ppi-portal-frontend/