# This is a basic workflow to help you get started with Actions

name: Deploy to Prod

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-scp:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout master
          uses: actions/checkout@v2
        - name: npm run build & tar.gz
          run: |
            npm install
            npm run build
            tar -czf build.tar.gz build/
        - name: Copy build to server
          uses: appleboy/scp-action@master
          with:
            host: portal.ppiuk.id
            username: ubuntu
            key: ${{ secrets.DEPLOY_KEY }}
            source: "build.tar.gz"
            target: "."
  deploy:
    needs: build-and-scp
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy to portal.ppiuk.id
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: portal.ppiuk.id
          key: ${{ secrets.DEPLOY_KEY }}
          username: ubuntu
          script: |
            tar -xzf ./build.tar.gz
            sudo rm -rf /var/www/ppi-portal-frontend
            sudo mv ./build/ /var/www/ppi-portal-frontend
            rm -rf ./build/